
-- Create the TMP_EMPLOYEES table
CREATE TABLE TMP_EMPLOYEES (
    EMP_ID      NUMBER PRIMARY KEY,
    EMP_NAME    VARCHAR2(100),
    SALARY      NUMBER(10,2),
    DEPARTMENT  VARCHAR2(50)
);

-- Insert demo data
INSERT INTO TMP_EMPLOYEES VALUES (101, 'John Doe', 5000, 'IT');
INSERT INTO TMP_EMPLOYEES VALUES (102, 'Alice Smith', 4500, 'HR');
INSERT INTO TMP_EMPLOYEES VALUES (103, 'Bob Johnson', 6000, 'Finance');
INSERT INTO TMP_EMPLOYEES VALUES (104, 'Emma Brown', 5500, 'IT');
INSERT INTO TMP_EMPLOYEES VALUES (105, 'Charlie Green', 4800, 'HR');
INSERT INTO TMP_EMPLOYEES VALUES (106, 'David White', 7000, 'Marketing');

-- Commit changes
COMMIT;

-- Verify data
SELECT * FROM TMP_EMPLOYEES;
